initial_robot_configuration:

  ###############################
  # Initial robot configuration #
  ###############################

  com: [0.0, 0.15, -0.20]
  amom: [0.0, 0.0, 0.0]
  lmom: [0.0, 0.0, 0.0]
  eef_ctrl:
    eef_frc_rf: [0.0, 0.0, 0.5]
    eef_frc_lf: [0.0, 0.0, 0.5]
    eef_frc_rh: [0.0, 0.0, 0.0]
    eef_frc_lh: [0.0, 0.0, 0.0]
  eef_pose:
    eef_rf: [1.0,    0.086, 0.15, -0.92,    1.0, 0.0, 0.0, 0.0]
    eef_lf: [1.0,   -0.086, 0.15, -0.92,    1.0, 0.0, 0.0, 0.0]
    eef_rh: [0.0,    0.400, 0.30,  0.00,    0.0, -0.70711, 0.70711, 0.0 ]
    eef_lh: [0.0,   -0.400, 0.30,  0.00,    0.70711, 0.0, 0.0,  0.70711 ]


contact_plan:

  ######################
  # Contact parameters #
  ######################

  num_contacts: [3, 3, 0, 0]
  effcnt_rf:
    cnt0: [0.0, 1.0,    0.086, 0.15, -0.92,    1.0, 0.0, 0.0, 0.0,           1.0]
    cnt1: [2.0, 4.5,    0.500, 0.45, -0.76,    0.9689, 0.0, -0.2474, 0.0,    1.0]
    cnt2: [6.0, 9.9,    0.450, 0.98, -0.27,    1.0, 0.0, 0.0, 0.0,           1.0]
  effcnt_lf:
    cnt0: [0.0, 2.5,   -0.086, 0.15, -0.92,    1.0, 0.0, 0.0, 0.0,           1.0]
    cnt1: [4.0, 6.5,   -0.080, 0.70, -0.52,    0.96891, 0.0,  0.2474, 0.0,   1.0]
    cnt2: [8.5, 9.9,   -0.080, 1.25, -0.25,    1.0, 0.0, 0.0, 0.0,           1.0]
  effcnt_rh:
  effcnt_lh:


planner_variables:

  #######################
  # Dynamics parameters #
  #######################

  heuristic: SoftConstraint  # Types: TrustRegion, SoftConstraint, TimeOptimization #
  n_act_eefs: 2
  time_step: 0.1
  time_horizon: 9.5
  external_force: [0.00, 0.00, 0.00]
  com_displacement: [0.20, 1.05, 0.6]
  num_com_viapoints: 0
  com_viapoints:
    via0: [2.50,    0.500, 0.45,  0.00]

  #####################
  # Timing parameters #
  #####################

  max_time_iterations: 100
  max_time_residual_tolerance: 1e-3
  min_time_residual_improvement: 1e-5

  ############################
  # Configuration parameters #
  ############################

  gravity: 9.81
  robot_mass: 60.00
  friction_coeff: 1.0
  friction_cone: LinearCone  # Types: LinearCone, SocCone #
  torque_range: [-200.0, 200.0]
  eff_offset_rf: [ 0.00,  0.00,  0.00]
  eff_offset_lf: [ 0.00,  0.00,  0.00]
  eff_offset_rh: [ 0.20,  0.00,  0.48]
  eff_offset_lh: [-0.20,  0.00,  0.48]
  cop_range_rf: [-0.03,  0.03, -0.08,  0.08]
  cop_range_lf: [-0.03,  0.03, -0.08,  0.08]
  cop_range_rh: [-0.03,  0.03, -0.03,  0.03]
  cop_range_lh: [-0.03,  0.03, -0.03,  0.03]
  max_eef_lengths: [0.82,  0.82,  0.60,  0.60]

  ####################
  # Dynamics weights #
  ####################

  w_trq_arm:       1.000
  w_trq_leg:       1.000
  w_com:           [ 10000,  10000,  10000]
  w_amom:          [ 0.500,  0.500,  0.500]
  w_lmom:          [ 0.010,  0.001,  0.001]
  w_amomd:         [ 0.100,  0.400,  0.100]
  w_lmomd:         [ 0.015,  0.015,  0.015]
  w_amom_final:    [ 10.00,  10.00,  10.00]
  w_lmom_final:    [ 10.00,  10.00,  10.00]
  w_com_via:       [ 0.000,  0.000,  0.000]
  w_frc_arm:       [ 0.001,  0.001,  0.001]
  w_frc_leg:       [ 0.001,  0.001,  0.001]
  w_dfrc_arm:      [ 0.000,  0.000,  0.000]
  w_dfrc_leg:      [ 0.000,  0.000,  0.000]
  w_amom_track:    [ 1.000,  1.000,  1.000]
  w_lmom_track:    [ 0.100,  0.100,  0.100]

  #######################
  # Storage information #
  #######################

  store_data: True

  ##################
  # Solver setting #
  ##################

  use_default_solver_setting: True
