is_record: false
servo_rate: 0.001 # !!this should be match with controller servo rate!!
show_joint_frame: false
hanging_height: 0.83
display_joint_frame: false
display_target_frame: true
joint_limit_enforced: true
initial_configuration: [0, 0, -0.5, 1.8, 1.03, 0, 0, -0.5, 1.8, 1.03]
plot_mpc_result: true

control_configuration:
  kp: [120 , 200 , 120 , 120 , 5 , 120 , 200 , 120 , 120 , 5]
  kd: [12  , 20  , 12  , 12  , 1  , 12  , 20  , 12  , 12  , 1]
