servo_rate: 0.001 # !!this should be match with controller servo rate!!
is_record: false
show_joint_frame: false
plot_mpc_result: false

# Low-level Joint PD gains
control_configuration:
  kp: 4 
  kd: 4

